---
- name: Linode Setup
  hosts: ethantwardy.com
  tasks:
    - name: Copy nftables ruleset
      ansible.builtin.copy:
        src: vps/forward-ssh.nft
        dest: /etc/nftables.nft.d/forward-ssh.nft
        owner: root
        group: root
        mode: '0644'
    - name: Enable ipv4 forwarding in sysctl.conf
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.conf
        sysctl_set: yes
        state: present
        reload: yes
