---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=30000
    volumes:
      - qbittorrent:/config
      - /mnt/Library/Torrents:/downloads
      - /mnt/TorrentFiles:/torrents
      - /mnt/Library/Seeding:/seeding
    restart: unless-stopped

networks:
  default:
    external:
      name: twardyece_front_net

volumes:
  qbittorrent:
    external: true
