FROM docker.io/jenkins/agent:latest

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 python3-pip \
    && apt-get clean

USER jenkins
ENV PATH="/home/jenkins/.local/bin:$PATH"
RUN python3 -m pip install setuptools wheel \
    && python3 -m pip install mkdocs-material

USER root
COPY jenkins-agent-cmd.sh /bin/jenkins-agent-cmd
CMD ["/bin/jenkins-agent-cmd"]
