upstream cimmeria {
    keepalive 32;
    server public_cimmeria:3000;
}

server {
    listen 80;
    listen [::]:80;
    server_name conan.ethantwardy.com;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://cimmeria;
        proxy_redirect http://cimmeria https://conan.ethantwardy.com;
    }
}
