upstream miniflux {
    keepalive 32;
    server public_miniflux:8080;
}

server {
    listen 80;
    listen [::]:80;
    server_name miniflux.ethantwardy.com;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://miniflux;
        proxy_redirect http://miniflux https://miniflux.ethantwardy.com;
    }
}
