version: "3.1"
services:
  openldap:
    container_name: "internal_ldap"
    image: "docker.io/osixia/openldap:stable"
    volumes:
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"

networks:
  default:
    external:
      name: twardyece_front_net

volumes:
  ldap:
    driver: local
    driver_opts: 
      type: btrfs
      o: subvol=@openldap_ldap-data
      device: /dev/sda4
  slapd.d:
    driver: local
    driver_opts: 
      type: btrfs
      o: subvol=@openldap_slapd-config
      device: /dev/sda4
