version: "2.4"
services:
  openldap:
    image: "docker.io/osixia/openldap:stable"
    volumes:
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"

networks:
  default:
    external:
      name: edtwardy-webservices_front_net

volumes:
  ldap:
    external: true
  slapd.d:
    external: true
