version: "2.4"
services:

  # Web server instance (the only external facing service)
  nginx:
    image: "docker.io/library/nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
      - "apps-media:/var/www/media:ro"
      - "apps-static:/var/www/static:ro"
      - "repository:/var/www/repository:ro"
      - "blog:/var/www/blog:ro"
      - "/mnt/Serve/yocto/sstate-cache:/data/yocto/sstate-cache:ro"
      - "/mnt/Serve/yocto/deploy:/data/yocto/deploy:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  openldap:
    image: "docker.io/osixia/openldap:stable"
    volumes:
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"

  apps:
    image: "docker.io/edtwardy/apps:latest"
    volumes:
      - "apps-database:/data/database"
      - "apps-media:/data/media"
      - "apps-static:/data/static:ro"
      - "apps-secrets:/data/secrets:ro"
    environment:
      - DJANGO_HOSTNAME=www.twardyece.com:twardyece.com
      - SCRIPT_NAME=/apps

  jenkins-controller:
    image: "docker.io/jenkins/jenkins:lts"
    volumes:
      - "jenkins:/var/jenkins_home"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      # TODO: This is a security risk, but is necessary in order for this
      # container to be able to bind to the LDAP server at
      # ldap://edtwardy-webservices_openldap_1
      - JENKINS_JAVA_OPTS=-Dcom.sun.jndi.ldapURLParsing="legacy"

  jenkins-agent:
    image: "docker.io/edtwardy/jenkins-agent:latest"
    init: true
    depends_on:
      - jenkins-controller
    volumes:
      - "repository:/home/jenkins/repository"
      - "blog:/home/jenkins/blog"
      - "agent-secret:/secrets:ro"
    environment:
      - REPOSITORY_MOUNT=/home/jenkins/repository
      - AGENT_NAME=docker-agent

  compilations:
    image: "docker.io/edtwardy/compilations:1.1.0"
    volumes:
      - "compilations-secret:/data:ro"
    environment:
      - TZ=America/Chicago

networks:
  default:
    external:
      name: edtwardy-webservices_front_net

volumes:
  siteconf:
    external: true
  letsencrypt:
    external: true
  ldap:
    external: true
  slapd.d:
    external: true
  apps-database:
    external: true
  apps-media:
    external: true
  apps-static:
    external: true
  jenkins:
    external: true
  agent-secret:
    external: true
  apps-secrets:
    external: true
  compilations-secret:
    external: true

  # The following volumes are ephemeral "default" volumes.
  acme-challenge:
  repository:
  blog:
