version: "2.4"
services:

  # Web server instance (the only external facing service)
  nginx:
    image: "docker.io/library/nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
      - "repository:/var/www/repository:ro"
      - "blog:/var/www/blog:ro"
      - "/mnt/Serve/yocto/sstate-cache:/data/yocto/sstate-cache:ro"
      - "/mnt/Serve/yocto/deploy:/data/yocto/deploy:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

  openldap:
    image: "docker.io/osixia/openldap:stable"
    volumes:
      - "ldap:/var/lib/ldap"
      - "slapd.d:/etc/ldap/slapd.d"

  jenkins-controller:
    image: "docker.io/jenkins/jenkins:lts"
    volumes:
      - "jenkins:/var/jenkins_home"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      # TODO: This is a security risk, but is necessary in order for this
      # container to be able to bind to the LDAP server at
      # ldap://edtwardy-webservices_openldap_1
      - JENKINS_JAVA_OPTS=-Dcom.sun.jndi.ldapURLParsing="legacy"

  jenkins-agent:
    image: "docker.io/edtwardy/jenkins-agent:1.0.0"
    init: true
    depends_on:
      - jenkins-controller
    volumes:
      - "repository:/home/jenkins/repository"
      - "blog:/home/jenkins/blog"
      - "agent-secret:/secrets:ro"
    environment:
      - REPOSITORY_MOUNT=/home/jenkins/repository
      - AGENT_NAME=docker-agent

  budget-tool:
    image: docker.io/edtwardy/budget-tool:0.3.0
    init: true
    depends_on:
      - postgres
    restart: always
    environment:
      - "DATABASE_URL=postgres://edtwardy-webservices_postgres_1:5432/budgets"
      - TZ=America/Chicago
    volumes:
      - "budget-tool-secret:/data:ro"

networks:
  default:
    external:
      name: edtwardy-webservices_front_net

volumes:
  siteconf:
    external: true
  letsencrypt:
    external: true
  ldap:
    external: true
  slapd.d:
    external: true
  jenkins:
    external: true
  agent-secret:
    external: true
  budget-tool-secret:
    external: true

  # The following volumes are ephemeral "default" volumes.
  acme-challenge:
  repository:
  blog:
