version: "3.1"
services:
  # Web server instance (the only external facing service)
  nginx:
    image: "docker.io/library/nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
      - "twardyece_repository:/var/www/repository:ro"
      - "twardyece_blog:/var/www/blog:ro"
      - "/mnt/Serve/yocto/sstate-cache:/data/yocto/sstate-cache:ro"
      - "/mnt/Serve/yocto/deploy:/data/yocto/deploy:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - TZ=America/Chicago

networks:
  default:
    external:
      name: twardyece_front_net

volumes:
  siteconf:
    driver: local
    driver_opts:
      type: "fuse.squashfuse"
      device: "/var/lib/twardyece-nginx/siteconf-volume.squashfs"
  letsencrypt:
    driver: local
    driver_opts: 
      type: btrfs
      o: subvol=@ssl_letsencrypt
      device: /dev/sda4
  twardyece_repository:
    external: true
  twardyece_blog:
    external: true

  # The following volumes are ephemeral "default" volumes.
  acme-challenge:
