version: "2.4"
services:
  # Web server instance (the only external facing service)
  nginx:
    image: "docker.io/library/nginx:stable-alpine"
    volumes:
      - "siteconf:/etc/nginx/conf.d:ro"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "acme-challenge:/var/www/certbot:ro"
      - "repository:/var/www/repository:ro"
      - "blog:/var/www/blog:ro"
      - "/mnt/Serve/yocto/sstate-cache:/data/yocto/sstate-cache:ro"
      - "/mnt/Serve/yocto/deploy:/data/yocto/deploy:ro"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

networks:
  default:
    external:
      name: edtwardy-webservices_front_net

volumes:
  siteconf:
    external: true
  letsencrypt:
    external: true

  # The following volumes are ephemeral "default" volumes.
  acme-challenge:
