version: "3.1"
services:
  tftp:
    container_name: internal_tftp
    image: docker.io/taskinen/tftp:latest
    ports:
      - "69:69/udp"
    volumes:
      - "/mnt/Serve/tftp:/var/tftpboot:ro"
    restart: unless-stopped
