version: "3.1"
services:
  jenkins-agent:
    image: "docker.io/edtwardy/jenkins-agent:latest"
    volumes:
      - "repository:/home/jenkins/repository"
      - "blog:/home/jenkins/blog"
      - "agent-secret:/secrets:ro"
    environment:
      - REPOSITORY_MOUNT=/home/jenkins/repository
      - AGENT_NAME=docker-agent
      - CONTROLLER_HOSTNAME=http://twardyece_jenkins-controller_1:8080

networks:
  default:
    external:
      name: twardyece_front_net

volumes:
  agent-secret:
    external: true

  # The following volumes are ephemeral "default" volumes.
  repository:
  blog:
