version: "2.4"
services:
  jenkins-controller:
    container_name: public_jenkins-controller
    image: "docker.io/jenkins/jenkins:lts"
    volumes:
      - "jenkins:/var/jenkins_home"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      # TODO: This is a minor security risk, but is necessary in order for this
      # container to be able to bind to LDAP servers with hyphens in the URI.
      - JENKINS_JAVA_OPTS=-Dcom.sun.jndi.ldapURLParsing="legacy"

networks:
  default:
    external:
      name: twardyece_front_net

volumes:
  jenkins:
    driver: local
    driver_opts: 
      type: btrfs
      o: subvol=@jenkins_controller-config
      device: /dev/sda4
