# Author: Ethan D. Twardy <ethan.twardy@gmail.com>
# Date: 16 Apr 2024
#
# sshd configuration for ethantwardy.com

AllowUsers ethantwardy root
# Unfortunately, the backup server needs to login as root
PermitRootLogin yes
PasswordAuthentication no
