version: "3.1"
services:
  compilations:
    image: "docker.io/edtwardy/compilations:latest"
    volumes:
      - "compilations-secret:/data:ro"
    environment:
      - TZ=America/Chicago

networks:
  default:
    external:
      name: edtwardy-webservices_front_net

volumes:
  compilations-secret:
    external: true
