.TH edtwardy-plex 8
.SH NAME
edtwardy-plex - convenient Bash script to start Plex in a container
.SH SYNOPSIS
.B edtwardy-plex
.IR command
.SH DESCRIPTION
.B edtwardy-plex
communicates with a Container Runtime Daemon to start, stop, or purge
Plex container instances from the system

The following commands are supported:
.TP
.BR start
Start Plex in the container (runs until interrupted)
