upstream tandoor {
    keepalive 32;
    server public_tandoor:8080;
}

server {
    listen 80;
    listen [::]:80;
    server_name recipes.ethantwardy.com;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://tandoor;
        proxy_redirect http://tandoor https://recipes.ethantwardy.com;
      }
}
